### ISSUE TITLE
'rake db:migrate' won't work on my machine

### ISSUE THREAD

**Issue by ghost** [colindean/plas#45] opened 2011-06-22 01:16 UTC
```
erad1cate@ubuntu:~/plas$ rake db:migrate
/home/erad1cate/.rvm/gems/ruby-1.9.2-p180@plas/gems/json-1.5.3/ext/json/ext/json/ext/parser.so: [BUG] Segmentation fault
ruby 1.8.7 (2010-08-16 patchlevel 302) [x86_64-linux]

Aborted
```

**Comment by colindean** [comment] 2011-06-22 01:28
Please provide the output of the following:
- rails --version
- ruby --version
- rvm current
- gem list
- cat /etc/lsb_release
- uname -a
- env
- git log | head

**Comment by ghost** [comment] 2011-06-23 01:17
erad1cate@ubuntu:~/plas$ rails --version
Rails 3.0.7

erad1cate@ubuntu:~/plas$ ruby --version
ruby 1.9.2p180 (2011-02-18 revision 30909) [x86_64-linux]

erad1cate@ubuntu:~/plas$ rvm current
ruby-1.9.2-p180@plas

erad1cate@ubuntu:~/plas$ gem list

**\* LOCAL GEMS ***

abstract (1.0.0)
actionmailer (3.0.9, 3.0.7)
actionpack (3.0.9, 3.0.7)
activemerchant (1.15.0)
activemodel (3.0.9, 3.0.7)
activerecord (3.0.9, 3.0.7)
activeresource (3.0.9, 3.0.7)
activesupport (3.0.9, 3.0.7)
ansi (1.2.5)
arel (2.0.10)
authlogic (3.0.3)
braintree (2.10.1, 2.10.0)
builder (2.1.2)
bundler (1.0.15, 1.0.14)
bzip2-ruby (0.2.7)
capybara (1.0.0)
childprocess (0.1.9)
erubis (2.6.6)
factory_girl (1.3.3)
factory_girl_rails (1.0.1)
fast_gettext (0.5.12)
ffi (1.0.9)
gettext (2.1.0)
gettext_i18n_rails (0.2.20)
i18n (0.5.0)
jquery-rails (1.0.11)
json (1.5.3)
json_pure (1.5.3)
locale (2.0.5)
mail (2.2.19)
mime-types (1.16)
money (3.7.1)
nokogiri (1.4.6)
polyglot (0.3.1)
rack (1.2.3)
rack-mount (0.6.14)
rack-test (0.5.7)
rails (3.0.9, 3.0.7)
railties (3.0.9, 3.0.7)
rake (0.9.2, 0.9.0, 0.8.7)
rcov (0.9.9)
rdoc (3.6.1)
rubyzip (0.9.4)
selenium-webdriver (0.2.1)
spork (0.8.5)
sqlite3 (1.3.3)
sqlite3-ruby (1.3.3)
steam-condenser (0.14.0)
thor (0.14.6)
treetop (1.4.9)
turn (0.8.2)
tzinfo (0.3.28, 0.3.27)
watchr (0.7)
xpath (0.1.4)

erad1cate@ubuntu:~/plas$ cat /etc/lsb_release
cat: /etc/lsb_release: No such file or directory

erad1cate@ubuntu:~/plas$ uname -a
Linux ubuntu 2.6.38-8-generic #42-Ubuntu SMP Mon Apr 11 03:31:24 UTC 2011 x86_64 x86_64 x86_64 GNU/Linux

erad1cate@ubuntu:~/plas$ env
rvm_dump_environment_flag=0
ORBIT_SOCKETDIR=/tmp/orbit-erad1cate
SSH_AGENT_PID=1402
rvm_clang_flag=0
GEM_HOME=/home/erad1cate/.rvm/gems/ruby-1.9.2-p180@plas
TERM=xterm
SHELL=/bin/bash
XDG_SESSION_COOKIE=399b03895ce6cdb691e43cf60000000a-1308791349.866096-865371347
IRBRC=/home/erad1cate/.rvm/rubies/ruby-1.9.2-p180/.irbrc
WINDOWID=60817446
OLDPWD=/home/erad1cate
GNOME_KEYRING_CONTROL=/tmp/keyring-pRi7n5
MY_RUBY_HOME=/home/erad1cate/.rvm/rubies/ruby-1.9.2-p180
GTK_MODULES=canberra-gtk-module
rvm_create_flag=1
USER=erad1cate
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:_.tar=01;31:_.tgz=01;31:_.arj=01;31:_.taz=01;31:_.lzh=01;31:_.lzma=01;31:_.tlz=01;31:_.txz=01;31:_.zip=01;31:_.z=01;31:_.Z=01;31:_.dz=01;31:_.gz=01;31:_.lz=01;31:_.xz=01;31:_.bz2=01;31:_.bz=01;31:_.tbz=01;31:_.tbz2=01;31:_.tz=01;31:_.deb=01;31:_.rpm=01;31:_.jar=01;31:_.rar=01;31:_.ace=01;31:_.zoo=01;31:_.cpio=01;31:_.7z=01;31:_.rz=01;31:_.jpg=01;35:_.jpeg=01;35:_.gif=01;35:_.bmp=01;35:_.pbm=01;35:_.pgm=01;35:_.ppm=01;35:_.tga=01;35:_.xbm=01;35:_.xpm=01;35:_.tif=01;35:_.tiff=01;35:_.png=01;35:_.svg=01;35:_.svgz=01;35:_.mng=01;35:_.pcx=01;35:_.mov=01;35:_.mpg=01;35:_.mpeg=01;35:_.m2v=01;35:_.mkv=01;35:_.ogm=01;35:_.mp4=01;35:_.m4v=01;35:_.mp4v=01;35:_.vob=01;35:_.qt=01;35:_.nuv=01;35:_.wmv=01;35:_.asf=01;35:_.rm=01;35:_.rmvb=01;35:_.flc=01;35:_.avi=01;35:_.fli=01;35:_.flv=01;35:_.gl=01;35:_.dl=01;35:_.xcf=01;35:_.xwd=01;35:_.yuv=01;35:_.cgm=01;35:_.emf=01;35:_.axv=01;35:_.anx=01;35:_.ogv=01;35:_.ogx=01;35:_.aac=00;36:_.au=00;36:_.flac=00;36:_.mid=00;36:_.midi=00;36:_.mka=00;36:_.mp3=00;36:_.mpc=00;36:_.ogg=00;36:_.ra=00;36:_.wav=00;36:_.axa=00;36:_.oga=00;36:_.spx=00;36:_.xspf=00;36:
rvm_path=/home/erad1cate/.rvm
SSH_AUTH_SOCK=/tmp/keyring-pRi7n5/ssh
SESSION_MANAGER=local/ubuntu:@/tmp/.ICE-unix/1369,unix/ubuntu:/tmp/.ICE-unix/1369
USERNAME=erad1cate
DEFAULTS_PATH=/usr/share/gconf/gnome.default.path
XDG_CONFIG_DIRS=/etc/xdg/xdg-gnome:/etc/xdg
PATH=/home/erad1cate/.rvm/gems/ruby-1.9.2-p180@plas/bin:/home/erad1cate/.rvm/gems/ruby-1.9.2-p180@global/bin:/home/erad1cate/.rvm/rubies/ruby-1.9.2-p180/bin:/home/erad1cate/.rvm/bin:/home/erad1cate/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
DESKTOP_SESSION=gnome
PWD=/home/erad1cate/plas
GDM_KEYBOARD_LAYOUT=us
GNOME_KEYRING_PID=1350
LANG=en_US.UTF-8
GDM_LANG=en_US.utf8
MANDATORY_PATH=/usr/share/gconf/gnome.mandatory.path
UBUNTU_MENUPROXY=libappmenu.so
COMPIZ_CONFIG_PROFILE=ubuntu
GDMSESSION=gnome
rvm_version=1.6.18
SHLVL=1
HOME=/home/erad1cate
LANGUAGE=en_US:en
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
LOGNAME=erad1cate
GEM_PATH=/home/erad1cate/.rvm/gems/ruby-1.9.2-p180@plas:/home/erad1cate/.rvm/gems/ruby-1.9.2-p180@global
XDG_DATA_DIRS=/usr/share/gnome:/usr/local/share/:/usr/share/
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-Sh6donKwmB,guid=57ac827cc2dbfe22dc9ddca50000002e
LESSOPEN=| /usr/bin/lesspipe %s
WINDOWPATH=7
DISPLAY=:0
RUBY_VERSION=ruby-1.9.2-p180
LESSCLOSE=/usr/bin/lesspipe %s %s
COLORTERM=gnome-terminal
XAUTHORITY=/var/run/gdm/auth-for-erad1cate-WrnHIy/database
_=/usr/bin/env

erad1cate@ubuntu:~/plas$ git log | head
commit 0395d9f58334977401f31072d9f3eaf036ee608c
Author: Colin Dean cdean@pittco.org
Date:   Mon Jun 20 20:48:08 2011 -0400

```
several gem updates
```

commit fc6c3475e68d56f41a72b9c5d2c95b861fd55d43
Author: Colin Dean cad@cad.cx
Date:   Fri Jun 17 00:02:58 2011 -0400

**Comment by colindean** [comment] 2011-06-23 01:25
do `gem remove json` and see if you can install 1.5.2. Maybe there's a
bug in 1.5.3? I won't be able to try it out on my Ubuntu box until I get
home Friday.

**Comment by ghost** [comment] 2011-06-23 01:42
No dice. I reinstalled 1.5.3 with nothing. 'gem install json-1.5.2' doesn't return anything but 'gem install json' installs 1.5.3.

**Comment by colindean** [comment] 2011-06-23 01:43
Look up the syntax for installing a specific version. I can't remember
it. I think it's `gem install json '= 1.5.2'`.

**Comment by ghost** [comment] 2011-06-23 01:48
erad1cate@ubuntu:~/plas$ rake db:migrate
rake aborted!
Could not find json-1.5.3 in any of the sources

(See full trace by running task with --trace)

**Comment by billturner** [comment] 2011-06-23 17:20
It should be left up to bundler to install any gems. I wonder if part of the problem could be with the newest rake, which did cause some problems more recently, esp. with one or two of the rails 3.0.x versions.

We might want to bump up the Rails version in the gemfile to the latest (3.0.9), and then make sure when you run rake, that you prepend it with "bundle exec":

bundle exec rake db:migrate

Edit: Some info here on why you should always use "bundle exec" for executables, here: http://yehudakatz.com/2011/05/30/gem-versioning-and-bundler-doing-it-right/

**Comment by colindean** [comment] 2011-06-23 17:39
Do it. Bump the rails version and try it out. 

I've actually been tempted to remove the version spec there anyway, at least until we have a real release out.

**Comment by ghost** [comment] 2011-06-27 00:29
No luck. Same error as before (first post). :(

**Comment by colindean** [comment] 2011-06-27 00:52
I'm looking at this presently. I'm seeing some potential problems introduced with rails 3.0.9, too. Signup form is broken on the date_select for birthdate.

**Comment by colindean** [comment] 2011-06-27 01:49
date_select for birthdate is a separate issue, not sure what happened there. ...regression tests would have caught that :-/

Do you have the freshest RVM installed?

```
bash < <(curl -s https://rvm.beginrescueend.com/install/rvm)
rvm reload
```

I'm currently reinstalling it and recompiling 1.9.2.

**Comment by colindean** [comment] 2011-06-27 02:43
OK, it's WFFM. Try updating your repo and trying again.

**Comment by ghost** [comment] 2011-06-27 21:37
Pulled and up-to-date from your branch. 

Getting same error.

Running "rails s" and going to localhost:3000 in my browser (firefox) gives me the following print out in the browser.

http://pastebin.com/VPQKfwHx

**Comment by colindean** [comment] 2011-06-27 22:49
Actually, that appears to be working, unless it can fire up without needing the migrations. It's my own stupidity's fault that I hardcoded `User.find(1)` in the sample shoutbox. Go to http://localhost:3000/users/new and create a new user. That user will be used on the shoutbox and you'll be able to do stuff normally.

**Comment by ghost** [comment] 2011-06-27 22:55
But why can't I migrate the db :(

**Comment by billturner** [comment] 2011-06-27 22:58
@erad1cate, can you copy/paste the output of this into a gist or pastebin:

```
bundle exec rake --trace db:migrate
```

that may show where the error is happening.

**Comment by colindean** [comment] 2011-06-28 00:40
Also, did you install all of the packages listed in `doc/CONTRIBUTING.mkd`? That tripped up @jungleralph just now.

**Comment by vidbina** [comment] 2011-09-11 22:23
Hey fellas has there been a real solution to this problem yet? I'm getting this error myself but sifting through all the different pages on Google didn't really get my out of this one. I don't get squat on the trace.

**Comment by colindean** [comment] 2011-09-11 22:35
You're doing this on Ubuntu, right? I never was able to reproduce it.

**Comment by vidbina** [comment] 2011-09-12 15:04
Yup (Natty Narwhal), but it's okay now. I ran `gem install rake` after which I ran `gem install rack` and everything seems to be working fine now. Guess I somehow overlooked a little detail while setting my environment up. #fail

**Comment by colindean** [comment] 2011-09-12 15:28
That's strange. Did you run `bundle install` at any point? Maybe it's missing a dependency somewhere.

## Erad1cate, can you try the above possible solution? 

Colin Dean 

David Asabina reply@reply.github.com wrote:

Yup (Natty Narwhal), but it's okay now. I ran `gem install rake` after which I ran `gem install rack` and everything seems to be working fine now. Guess I somehow overlooked a little detail while setting my environment up. #fail

##

**Comment by vidbina** [comment] 2011-09-12 21:37
I did try `bundle install` many times to no avail because I already suspected broken dependencies. Somehow I had to run the manual installs for the gems while the Gemfile seemed to have all the necessary gems listed for installation. I'm baffled; I have no idea what really happened but I guess that is largely due to the fact that I'm new to Ruby. For now it seems to work now alright.

**Comment by colindean** [comment] 2011-09-12 21:57
Great! Well, thanks for helping out! Let me know if you have any 
questions.

**Comment by colindean** [comment] 2011-09-15 00:49
I just ran through doc/CONTRIBUTING.mkd and updated where necessary. It was a little out of date, but I don't see anything in there which would have caused the problem. That doesn't mean it wasn't in there!

I ran through the process on a new lucid vm and it worked fine. I might try later on a natty vm (just not as readily available via Vagrant).

**Comment by colindean** [comment] 2011-09-20 01:05
Ritter, any luck?

**Comment by colindean** [comment] 2011-11-05 04:08
@kingvidbina or @erad1cate -- did you ever get this working?

**Comment by vidbina** [comment] 2011-11-05 09:56
I've been there since september 12 ;)

**Comment by colindean** [comment] 2011-11-05 16:33
Great! Have you had a chance to hack on it at all? Do you have any questions? If so, shoot me an email or a PM.

Now, to get @erad1cate's working...

**Comment by colindean** [comment] 2011-11-30 04:04
I'm closing this. @erad1cate, let me know in person if you still can't get it to work.

**Closed as completed by colindean** 2011-11-30 04:04 UTC
Labels: Defect, Critical
